[package]
name = "subtensor-tools"
version = "0.1.0"
edition = "2021"
license = "MIT"

description = "support tools for Subtensor"
repository = "https://github.com/opentensor/subtensor"
homepage = "https://bittensor.com"

[[bin]]
name = "bump-version"
path = "src/bump_version.rs"

[dependencies]
anyhow = { workspace = true }
clap = { version = "4.5", features = ["derive"] }
semver = "1.0"
toml_edit = "0.22"
