[package]
name = "share-pool"
version = "0.1.0"
edition = "2021"

[dependencies]
substrate-fixed = { workspace = true }
sp-std = { workspace = true }
safe-math = { default-features = false, path = "../safe-math" }

[lints]
workspace = true

[features]
default = ["std"]
std = [
	"substrate-fixed/std",
	"sp-std/std",
	"safe-math/std",
]
