name: cargo audit
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
concurrency:
  group: cargo-audit-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cargo-audit:
    name: cargo audit
    runs-on: SubtensorCI
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip-cargo-audit') }}
    steps:
      - name: Check-out repositoroy under $GITHUB_WORKSPACE
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update &&
          sudo apt-get install -y clang curl libssl-dev llvm libudev-dev protobuf-compiler

      - name: Install cargo-audit
        run: cargo install --version 0.20.1 --force cargo-audit

      - name: Display cargo-audit --version
        run: cargo audit --version

      - name: cargo audit
        run: cargo audit --ignore RUSTSEC-2024-0336 # rustls issue; wait for upstream to resolve this
